export const Produclist = [
{
    Image: "src/assets/Product/Cooling/DEEPCOOL DP-FRGB-RF120-3C RF 120-3 in 1 RGB Fans.png",
    Model: "DEEPCOOL DP-FRGB-RF120-3C RF 120-3 in 1 RGB Fans",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,699.00",
    Category: "cooling",
},
{
    Image: "src/assets/Product/Cooling/Deepcool FC120 3 in 1 RGB.png",
    Model: "Deepcool FC120 3 in 1 RGB Silent Operation Up to 1800 RPM Fan Speed PWM Cooling Fan White or Black",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,530.00",
    Category: "cooling",
},
{
    Image: "src/assets/Product/Cooling/DEEPCOOL FK120 Fan.png",
    Model: "DEEPCOOL FK120 Fan (R-FK120-BKNPF1-G-1)",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 465.50",
    Category: "cooling",
},
{
    Image: "src/assets/Product/Cooling/DEEPCOOL Gammaxx L360 ARGB.png",
    Model: "DEEPCOOL Gammaxx L360 ARGB liquid cooling system with Anti-Leak Technology DP-H12CF-GL360-ARGB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,899.00",
    Category: "cooling",
},
{
    Image: "src/assets/Product/Cooling/DEEPCOOL Ice Edge Mini FS V2.0 CPU Cooler.png",
    Model: "DEEPCOOL Ice Edge Mini FS V2.0 CPU Cooler",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 299.00",
    Category: "cooling",
},
{
    Image: "src/assets/Product/Cooling/DEEPCOOL LS520 SE 240mm Liquid CPU Cooler.png",
    Model: "DEEPCOOL LS520 SE 240mm Liquid CPU Cooler",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,328.00",
    Category: "cooling",
},
{
    Image: "src/assets/Product/GPU/ASUS DUAL GeForce RTX 4060 Ti 8GB.png",
    Model: "ASUS DUAL GeForce RTX 4060 Ti 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 27,510.00",
    Category: "gpu",
},
{
    Image: "src/assets/Product/GPU/ASUS TUF Gaming GeForce RTX 4080 (2).png",
    Model: "ASUS TUF Gaming GeForce RTX 4080 16GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 84,200.00",
    Category: "gpu",
},
{
    Image: "src/assets/Product/GPU/Gigabyte GeForce RTX 4070 Ti (1).png",
    Model: "Gigabyte GeForce RTX 4070 Ti Gaming OC V2 12GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 53,150.00",
    Category: "gpu",
},
{
    Image: "src/assets/Product/GPU/Gigabyte GeForce RTX 4070 WINDFORCE 12G (2).png",
    Model: "Gigabyte GeForce RTX 4070 WINDFORCE 12GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 43,995.00",
    Category: "gpu",
},
{
    Image: "src/assets/Product/GPU/MSI GeForce RTX 4060 GAMING X 8GB.png",
    Model: "MSI GeForce RTX 4060 GAMING X 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 20,630.00",
    Category: "gpu",
},
{
    Image: "src/assets/Product/GPU/MSI GeForce RTX 4090 SUPRIM X 24G (2).png",
    Model: "MSI GeForce RTX 4090 SUPRIM X 24GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 116,995.00",
    Category: "gpu",
},
{
    Image: "src/assets/Product/HDD/Seagate HDD green 1TB.png",
    Model: "Seagate HDD green 1TB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,285.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Seagate HDD green 2TB.png",
    Model: "Seagate HDD green 2TB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,779.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Seagate HDD green 500GB.png",
    Model: "Seagate HDD green 500GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,149.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Toshiba HDD 1TB.png",
    Model: "Toshiba HDD 1TB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,329.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Toshiba HDD 2TB.png",
    Model: "Toshiba HDD 2TB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,849.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Toshiba HDD 500GB.png",
    Model: "Toshiba HDD 500GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,253.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Western Digital HDD blue 1TB.png",
    Model: "Western Digital HDD blue 1TB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,253.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Western Digital HDD blue 2TB.png",
    Model: "Western Digital HDD blue 2TB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,915.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/HDD/Western Digital HDD blue 500GB.png",
    Model: "Western Digital HDD blue 500GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,715.00",
    Category: "hdd",
},
{
    Image: "src/assets/Product/Laptop/Acer/Nitro 5 AN515-58-55LG/Nitro5AN515-58(1).png",
    Model: "Acer Nitro 5 AN515-58-55LG",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 60,799.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Acer/Nitro AN515-46-R4W2/NitroAN515-46 (2).png",
    Model: "Acer Nitro AN515-46-R4W2",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 59,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Acer/Predator H elios 300 PH16-71-95L8/Acer-Helios-300-PH16-71-95L8 (1).png",
    Model: "Acer Predator Helios 300 PH16-71-95L8",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 129,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Acer/Predator Helios 300 PH16-71-72VB/PredatorHelios300-PH16-71 (3).png",
    Model: "Acer Predator Helios 300 PH16-71-72VB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 109,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Acer/Swift GO EVO Laptop SFG-14-71-70PY/swift-Go-EVO (1).png",
    Model: "Acer Swift Go EVO SFG14-71-70PY OPI",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 62,699.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Asus/Asus FA617NS-N3079W TUF/FA617NS-N3083W2 (2).png",
    Model: "Asus FA617NS-N3079W TUF",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 79,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Asus/Asus FX506HC-HN111W/asus-FX506HC (1).png",
    Model: "Asus FX506HC-HN111W",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 53,995.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Asus/Asus X1402ZA-EB110WS+OFFC H&S/asus-X1402ZA (2).png",
    Model: "Asus X1402ZA-EB110WS+OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 38,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Asus/Asus X1605ZA-MB236WS+OFFC H&S/asus-X1605ZA-MB23 (3).png",
    Model: "Asus X1605ZA-MB236WS+OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 50,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Asus/Asus M1605YA-MB155WS+OFFC H&S/asusM1605YA (5).png",
    Model: "Asus M1605YA-MB155WS+OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 37,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Dell/Dell IN3510 Platinum Silver + OFFC H&S/dell-IN3510 (4).png",
    Model: "Dell IN3510 Platinum Silver + OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 32,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Dell/Dell IN3511 Platinum Silver + OFFC H&S 15.6 fhd/dell-IN3511 (1).png",
    Model: "Dell IN3511 Platinum Silver + OFFC H&S 15.6 fhd",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 54,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Dell/Dell IN5410 Peach Dust +OFFC H&S/dell-IN5410=peach (1).png",
    Model: "Dell IN5410 Peach Dust +OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 52,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Dell/Dell IN5510 Platinum Silver + OFFC H&S/dell-IN5510 (2).png",
    Model: "Dell IN5510 Platinum Silver + OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 48,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Dell/Dell XPS 17 9710 TouchScreen Platimun Silver/dell-XPS (3).png",
    Model: "Dell XPS 17 9710 TouchScreen Platimun Silver",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 199,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/HP/HP 14-DV2029TX Warm Gold +H&S/hp-14-DV2029TX (1).png",
    Model: "HP 14-DV2029TX Warm Gold +H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 57,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/HP/HP 15-FC0049AU +OFFC H&S Natural Silver/HP-15-FC0049AU (4).png",
    Model: "HP 15-FC0049AU +OFFC H&S Natural Silver",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 38,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/HP/HP 15S-FQ2728TU Natural Silver + H&S/hp-FQ2728TU (1).png",
    Model: "HP 15S-FQ2728TU Natural Silver + H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 32,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/HP/HP ENVY X360 13-BF0110TU +OFFC H&S/HP-ENVY (1).png",
    Model: "HP ENVY X360 13-BF0110TU +OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 89,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/HP/HP X360 14-EK0121TU Space Blue +OFFC H&S/HP-X360 (1).png",
    Model: "HP X360 14-EK0121TU Space Blue +OFFC H&S",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 49,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Lenovo/Legion Pro 7i (16, Gen 8)/LEGION-PRO-7i (3).png",
    Model: "Legion Pro 7i",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 187,985.75",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Lenovo/Legion Slim 7i (16, Gen 8)/LEGION-SLIM (2).png",
    Model: "Legion Slim 7i",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 144,995.01",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Lenovo/LOQ (15, gEN 8)/LOQ-15IRH8 (2).png",
    Model: "LOQ 15",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 77,995.01",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Lenovo/ThinkPad E14 G5/thinkpad-E14-G5 (8).png",
    Model: "ThinkPad E14 G5",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 67,995.01",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/Lenovo/ThinkPad E16 G1/THINKPAD-E16-G1 (4).png",
    Model: "ThinkPad E16 G1",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 72,995.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/msi/MSI CYBORG 15 A12VE-444PH/CYBORG-15 (5).png",
    Model: "MSI CYBORG 15 A12VE-444PH",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 70,995.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/msi/MSI GF63 THIN 11UCX - 1479PH/MSI-GF63 (2).png",
    Model: "MSI GF63 THIN 11UCX - 1479PH",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 43,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/msi/MSI GF63 THIN 12VE-088PH/MSI-GF63-THIN (1).png",
    Model: "MSI GF63 THIN 12VE-088PH",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 69,995.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/msi/MSI Modern 14 C11M-220PH Beige/MSI-MODERN-14 (2).png",
    Model: "MSI Modern 14 C11M-220PH Beige",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 28,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Laptop/msi/MSI Modern 15 B11M-027PH Classic Black/MSI-MODERN-15 (2).png",
    Model: "MSI Modern 15 B11M-027PH Classic Black",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 37,999.00",
    Category: "laptop",
},
{
    Image: "src/assets/Product/Power Supply/Deepcool DQ750-M V2L 750W/06-removebg-preview.png",
    Model: "Deepcool DQ750-M V2L 750W Power Supply Unit (DP-DQ750-M-V2L)",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 5,375.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Deepcool PK550D - 550W/06-44-removebg-preview.png",
    Model: "Deepcool PK550D - 550W",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,662.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Deepcool PX1000G ATX 3.0/32_original-removebg-preview.png",
    Model: "Deepcool PX1000G ATX 3.0",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 10,000.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte Aorus P1200W Platinum/17-233-033-V03-removebg-preview.png",
    Model: "Gigabyte Aorus P1200W Platinum",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 18,530.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte GP-P650B 650W 80+ Bronze PSU/1000__3_-removebg-preview.png",
    Model: "Gigabyte GP-P650B 650W 80+ Bronze PSU",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,099.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte GP-UD1000GM-PG5 1000W/17-233-034-V07-removebg-preview.png",
    Model: "Gigabyte GP-UD1000GM-PG5 1000W PCIe 5.0 80 Plus Gold Certified Fully Modular Power Supply",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 9,250.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte P550B 80 PLUS Bronze/Gigabyte P550B (1).png",
    Model: "Gigabyte P550B 80 PLUS Bronze certified 550 Watts Power Supply Unit",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,531.45",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte UD750GM - 750W/17-233-037-V07-removebg-preview.png",
    Model: "Gigabyte UD750GM - 750W, Active PFC, ATX 12V, Ultra Durable 80 PLUS Gold certified PSU (GP-UD750GM)",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 5,499.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte UD850GM - 850W/17-233-036-V07-removebg-preview.png",
    Model: "Gigabyte UD850GM - 850W, Active PFC, Ultra Durable 80 PLUS Gold certified PSU - GP-UD850GM",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 6,052.80",
    Category: "psu",
},
{
    Image: "src/assets/Product/Power Supply/Gigabyte UD1300GM 1300W/17-233-042-07-removebg-preview.png",
    Model: "Gigabyte UD1300GM 1300W 80+ Gold PCIe Gen5 ATX3.0 Modular PSU (GP-UD1300GM PG5)",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 14,789.00",
    Category: "psu",
},
{
    Image: "src/assets/Product/Processor/AMD Ryzen 3 3200G (2).png",
    Model: "AMD Ryzen™ 3 3200G",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,999.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/AMD Ryzen 5 5600X.png",
    Model: "AMD Ryzen™ 5 5600X",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 8,780.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/AMD Ryzen 5 5700x.png",
    Model: "AMD Ryzen 5 5700x",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 10,299.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/AMD Ryzen 7 5700X.png",
    Model: "AMD Ryzen 7 5700X",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 10,695.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/AMD Ryzen 7 5800X.png",
    Model: "AMD Ryzen 7 5800X",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 13,795.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/AMD Ryzen 9 7900.png",
    Model: "AMD Ryzen 9 7900",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 26,999.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/Intel Core i3-12100F.png",
    Model: "Intel Core i3-12100F",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,998.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/Intel Core i3-13100F.png",
    Model: "Intel Core i3-13100F",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 7,625.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/Intel Core i5-13400F.png",
    Model: "Intel Core i5-13400F",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 12,799.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/Intel Core i7-13700K.png",
    Model: "Intel Core i7-13700K",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 26,295.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/Intel Core i9 13900K.png",
    Model: "Intel Core i9 13900K",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 38,599.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/Processor/Intel I9 12900K.png",
    Model: "Intel Core i9-12900K",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 27,968.00",
    Category: "cpu",
},
{
    Image: "src/assets/Product/RAM/Kingston FURY Beast DDR4 RGB.png",
    Model: "Kingston FURY Beast DDR4 RGB 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,550.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/RAM/Kingston FURY Beast DDR4.png",
    Model: "Kingston FURY Beast DDR4 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,050.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/RAM/Kingston FURY Beast DDR5 RGB.png",
    Model: "Kingston FURY Beast DDR5 RGB 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,695.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/RAM/Kingston FURY Beast DDR5.png",
    Model: "Kingston FURY Beast DDR5 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 6,850.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/RAM/Team_Elite DARK Za BLACK DDR4.png",
    Model: "Team Elite DARK Za BLACK DDR4 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,254.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/RAM/Team-group DELTA RGB DDR4.png",
    Model: "Team-group DELTA RGB DDR4 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,099.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/RAM/Team-group DELTA RGB DDR5.png",
    Model: "Team-group DELTA RGB DDR5 8GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,099.00",
    Category: "ram",
},
{
    Image: "src/assets/Product/SSD/Kingston NV2 1TB M.2 2280 PCIe4.0x4 NVMe SSD.png",
    Model: "Kingston NV2 1TB M.2 2280 PCIe4.0x4 NVMe SSD",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,199.00",
    Category: "ssd",
},
{
    Image: "src/assets/Product/SSD/Kingston SSD A400 SSD.png",
    Model: "Kingston SSD A400 SSD 240GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 1,429.00",
    Category: "ssd",
},
{
    Image: "src/assets/Product/SSD/Ramsta S800 2.5 SATA 3 SSD.png",
    Model: "Ramsta S800 2.5 SATA 3 SSD 256GB",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 789.00",
    Category: "ssd",
},
{
    Image: "src/assets/Product/SSD/Samsung 970 EVO Plus 1TB NVMe M.2 PCIe.png",
    Model: "Samsung 970 EVO Plus 1TB NVMe M.2 PCIe Gen 3.0 x4 Internal Solid State Drive",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,199.00",
    Category: "ssd",
},
{
    Image: "src/assets/Product/Motherboard/Asrock/A320M-HDV/A320M-HDV1.png",
    Model: "Asrock A320M-HDV",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,586.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asrock/B250M Pro4/B250M_Pro4_L1_-removebg-preview.png",
    Model: "Asrock B250M Pro4",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,999.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asrock/B450 Steel Legend/B450_Steel_Legend_L1_-removebg-preview.png",
    Model: "Asrock B450 Steel Legend",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 5,669.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asrock/B450M Steel Legend/B450M_Steel_Legend_L1_-removebg-preview.png",
    Model: "Asrock B450M Steel Legend",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 5,914.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asrock/Z370 Pro4/Z370_Pro4_L1_-removebg-preview.png",
    Model: "Asrock Z370 Pro4",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,646.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asus/EX-A320M-Gaming/1001-removebg-preview.png",
    Model: "Asus EX-A320M-Gaming",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,960.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asus/Prime A320M-K/23-removebg-preview.png",
    Model: "Asus Prime A320M-K",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,350.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asus/Prime Z390-A/33-removebg-preview.png",
    Model: "Asus Prime Z390-A",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 14,045.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asus/ROG Rampage II Extreme/53-removebg-preview.png",
    Model: "Asus ROG Rampage II Extreme",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 20,349.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asus/X99-Deluxe/X99-Deluxe-6-removebg-preview.png",
    Model: "Asus X99-Deluxe",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 19,330.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Asus/Z170 Pro Gaming/Z170_Pro_Gaming-4-removebg-preview.png",
    Model: "Asus Z170 Pro Gaming",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 8,427.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Colorful/C.A320M-K Pro V14/201908280952502990-removebg-preview.png",
    Model: "Colorful C.A320M-K Pro V14",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,977.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Gigabyte/B450 Aorus Elite/21214-removebg-preview.png",
    Model: "Gigabyte B450 Aorus Elite",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 7,192.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Gigabyte/GA-H110-D3A/GA-H110-D3A-4-removebg-preview.png",
    Model: "Gigabyte GA-H110-D3A",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,140.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Gigabyte/GA-H110M-DS2/GA-H110M-DS2-4-removebg-preview.png",
    Model: "Gigabyte GA-H110M-DS2",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 5,519.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Gigabyte/Gigabyte GA-A320M-S2H/GA-A320M-S2H-5-removebg-preview.png",
    Model: "Gigabyte GA-A320M-S2H",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 3,144.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Gigabyte/Z370P D3/Z370P_D3-5-removebg-preview.png",
    Model: "Gigabyte Z370P D3",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 7,800.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/Gigabyte/Z390 UD/Z390_UD-5-removebg-preview.png",
    Model: "Gigabyte Z390 UD",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 7,020.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/MSI/A320MH/b20190603_1-removebg-preview.png",
    Model: "Biostar A320MH",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,699.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/MSI/B350M Gaming Pro/1024-removebg-preview.png",
    Model: "MSI B350M Gaming Pro",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,288.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/MSI/B450M Pro-VDH/B450M_Pro-VDH-5-removebg-preview.png",
    Model: "MSI B450M Pro-VDH",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 4,579.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/MSI/H110M PRO-VH Plus/H110M_PRO-VH_Plus-5-removebg-preview.png",
    Model: "MSI H110M PRO-VH Plus",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 2,763.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/MSI/MPG X570 Gaming Edge Wifi/49731226-removebg-preview.png",
    Model: "MSI MPG X570 Gaming Edge Wifi",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 11,415.00",
    Category: "motherboard",
},
{
    Image: "src/assets/Product/Motherboard/MSI/Z390-A Pro/Z390-A_Pro-5-removebg-preview.png",
    Model: "MSI Z390-A Pro",
    Rating: "⭐⭐⭐⭐⭐",
    Price: "PHP 6,599.00",
    Category: "motherboard",
}
]

export const BestSellerCard = [
  {
    Image:
      'src/assets/Product/Laptop/Acer/Nitro 5 AN515-58-55LG/Nitro5AN515-58(1).png',
    Model: 'Acer Nitro 5 AN515-58-55LG',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 60,799',
    Category: 'Laptop',
  },
  {
    Image: 'src/assets/Product/Motherboard/Asrock/A320M-HDV/A320M-HDV1.png',
    Model: 'Asrock A320M-HDV',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 2,200',
    Category: 'Motherboard',
  },
  {
    Image: 'src/assets/Product/Processor/AMD Ryzen 9 7900.png',
    Model: 'AMD Ryzen™ 9 7900',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 26,999',
    Category: 'Processor',
  },
  {
    Image: 'src/assets/Product/RAM/Kingston FURY Beast DDR4 RGB.png',
    Model: 'Kingston FURY Beast DDR4 RGB',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 7,749',
    Category: 'RAM',
  },
  {
    Image:
      'src/assets/Product/Power Supply/Gigabyte Aorus P1200W Platinum/17-233-033-V08(1).png',
    Model: 'Gigabyte Aorus P1200W Platinum ',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 18,530',
    Category: 'Power Supply',
  },
  {
    Image: 'src/assets/Product/GPU/MSI GeForce RTX 4090 SUPRIM X 24G.png',
    Model: 'MSI GeForce RTX 4090 SUPRIM X 24G',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 116,995',
    Category: 'GPU',
  },
  {
    Image: 'src/assets/Product/HDD/Seagate HDD green 1TB.png',
    Model: 'Seagate HDD green 1TB',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 2,880',
    Category: 'HDD',
  },
  {
    Image: 'src/assets/Product/SSD/Ramsta S800 2.5 SATA 3 SSD.png',
    Model: 'Ramsta S800 2.5 SATA 3 SSD',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 940',
    Category: 'SSD',
  },
  {
    Image:
      'src/assets/Product/Cooling/DEEPCOOL Gammaxx L360 ARGB liquid cooling system with Anti-Leak Technology DP-H12CF-GL360-ARGB.png',
    Model: 'Deepcool Gammaxx L360 ARGB',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 4,899',
    Category: 'Cooling System',
  },
];

export const NewArrivalsCard = [
  {
    Image: 'src/assets/Product/Processor/Intel Core i9 13900K.png',
    Model: 'Intel Core i9-13900k',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 38,599',
    Category: 'Processor',
  },
  {
    Image: 'src/assets/Product/GPU/ASUS DUAL GeForce RTX 4060 Ti 8GB.png',
    Model: 'ASUS Dual GeForce RTX™ 4060 Ti 8GB',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 30,530',
    Category: 'GPU',
  },
  {
    Image: 'src/assets/Product/RAM/Team-group DELTA RGB DDR4.png',
    Model: 'Team-group DELTA RGB DDR4',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 6,350',
    Category: 'RAM',
  },
  {
    Image: 'src/assets/Product/HDD/Western Digital HDD blue 1TB.png',
    Model: 'Western Digital HDD Blue 1TB',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 2,790',
    Category: 'HDD',
  },
  {
    Image:
      'src/assets/Product/SSD/Kingston NV2 1TB M.2 2280 PCIe4.0x4 NVMe SSD.png',
    Model: 'Kingston NV2 1TB M.2 2280 PCIe4.0x4 NVMe SSD',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 1,688',
    Category: 'SSD',
  },
  {
    Image:
      'src/assets/Product/Power Supply/Deepcool PX1000G ATX 3.0/Deepcool PX1000G (1).png',
    Model: 'Deepcool PX1000G ATX 3.0 Power Supply 80 Plus GOLD',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 10,000',
    Category: 'Power Supply',
  },
  {
    Image:
      'src/assets/Product/Cooling/DEEPCOOL LS520 SE 240mm Liquid CPU Cooler.png',
    Model: 'Deepcool LE520 Water Cooling System For PC',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 3,328',
    Category: 'Cooling System',
  },
  {
    Image:
      'src/assets/Product/Motherboard/MSI/B350M Gaming Pro/1024__1_-removebg-preview.png',
    Model: 'MSI B350M Gaming Pro',
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 30,000',
    Category: 'Motherboard',
  },
  {
    Image:
      'src/assets/Product/Laptop/Lenovo/Legion Pro 7i (16, Gen 8)/LEGION-PRO-7i (1).png',
    Model: "Lenovo Legion Pro 7i (16', Gen 8)",
    Rating: '⭐⭐⭐⭐⭐',
    Price: 'PHP 187,985',
    Category: 'Laptop',
  },
];
